function cellInfo = InitOnboardMatlab_bus(varargin) 
% INITONBOARDMATLAB_BUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'CTRL_MODE', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'ctrl_mode', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'ctrl_enabled', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'disable_motor_onoff_by_stick', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'flight_mode', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'GPS_DATA_IN', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'gps_latitude', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_longitude', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_height', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_speed_EW', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_speed_NS', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_heading', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_position_acc', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_height_acc', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_speed_acc', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_num_sat', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_status', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_time_of_week', 1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_time_week', 1, 'uint16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'IMU_DATA_IN', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'angle_roll', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'angle_pitch', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'angle_yaw', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'angvel_roll', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'angvel_pitch', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'angvel_yaw', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'acc_x', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'acc_y', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'acc_z', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'Hx', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'Hy', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'Hz', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'height_data_fusion', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'dheight_data_fusion', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'data_fusion_speed_EW', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'data_fusion_speed_NS', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_latitude_data_fusion', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gps_longitude_data_fusion', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'LL_CMD_OUT', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'motor_rpm_1', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_rpm_2', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_rpm_3', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_rpm_4', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_rpm_5', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_rpm_6', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_mapped_roll', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_mapped_pitch', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_mapped_yaw', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'motor_mapped_thrust', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'att_cmd_roll', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'att_cmd_pitch', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'att_cmd_yaw', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'att_cmd_thrust', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'MOTOR_DATA_IN', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'m1', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'m2', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'m3', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'m4', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'m5', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'m6', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'RC_DATA_IN', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'CMD_1', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'CMD_2', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'CMD_3', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'CMD_4', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'CMD_5', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'CMD_6', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'CMD_7', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'CMD_8', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'UART_DATA_IN', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'uart_ctrl_01', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_02', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_03', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_04', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_05', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_06', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_07', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_08', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_09', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_10', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_11', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_ctrl_12', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'UART_DATA_OUT', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'uart_debug_01', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_02', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_03', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_04', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_05', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_06', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_07', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_08', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_09', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_10', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_11', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_12', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_13', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_14', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_15', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_16', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_17', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_18', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_19', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'uart_debug_20', 1, 'int16', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
